<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="1" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="18579" started-at="2022-12-24T17:44:17Z" finished-at="2022-12-24T17:44:35Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="18579" started-at="2022-12-24T17:44:17Z" finished-at="2022-12-24T17:44:35Z">
      <class name="com.upax.appium.zeus.Login">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.upax.appium.zeus.Login@5276e6b0]" name="setUp" is-config="true" duration-ms="18489" started-at="2022-12-24T11:44:17Z" finished-at="2022-12-24T11:44:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="TestMethod()[pri:0, instance:com.upax.appium.zeus.Login@5276e6b0]" name="TestMethod" duration-ms="16" started-at="2022-12-24T11:44:35Z" finished-at="2022-12-24T11:44:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestMethod -->
        <test-method status="FAIL" signature="testend()[pri:0, instance:com.upax.appium.zeus.Login@5276e6b0]" name="testend" is-config="true" duration-ms="0" started-at="2022-12-24T11:44:35Z" finished-at="2022-12-24T11:44:35Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.upax.appium.zeus.Login.testend(Login.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:225)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:114)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testend -->
      </class> <!-- com.upax.appium.zeus.Login -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
